### ISSUE TITLE
Document SFSE plugins

### ISSUE THREAD

**Issue by pStyl3** [loot/starfield#12]
<details>
  <summary>Preface</summary>

In masterlists we frequently create `File Anchors` in the `common` section, e.g.
```yaml
  - &JContainers
    name: 'SKSE/Plugins/JContainers64.dll'
    display: '[JContainers SE](https://www.nexusmods.com/skyrimspecialedition/mods/16495/)'
```
so that we can add these as requirements for plugins (in the `plugins` section), e.g.:
```yaml
  - name: 'Example.esp'
    req: [ *JContainers ]
```

In addition to the above, we also check if the Script Extender is correctly installed.

`prelude.yaml`
```yaml
  - &scriptExtenderMissing
    type: error
    content:
      - lang: en
        text: 'You have installed an {0} plugin but {0} was not found! See {0} download page: {1}.'
      # Other languages omitted for brevity
```
SSE's `masterlist.yaml` - `globals` section
```yaml
# SKSE
  # Missing AE
  - <<: *scriptExtenderMissing
    subs:
      - 'SKSE'
      - '[Skyrim Script Extender](https://skse.silverlock.org) Anniversary Edition'
    condition: 'readable("../SkyrimSE.exe") and not file("../Galaxy64.dll") and not file("../EOSSDK-Win64-Shipping.dll") and product_version("../SkyrimSE.exe", "1.6.317.0", >=) and not file("../skse64_loader.exe") and file("SKSE/Plugins/([^\.]+\.dll)")'
```

These checks reference Script Extender plugins, so files that were made using the feature set of the Script Extender, are stored in `SKSE/Plugins/` (in the case of SSE) and end in `.dll`.

[SFSE](https://www.nexusmods.com/starfield/mods/106/) has been created for Starfield and is likely to get updated and expanded over time.
</details>

In order to get "the lay of the land", I've started to create a list of already available [SFSE](https://www.nexusmods.com/starfield/mods/106/) plugins. We may or may not reference these files in our Starfield masterlist at some point, so this issue's sole purpose is to document what SFSE plugins there are right now.

After a few weeks or months this can be closed.

| Name | Link |
|---|---|
| AdsFovRemoved.dll | [ADS FOV Removed (SFSE)](https://www.nexusmods.com/starfield/mods/2192/) |
| auto_backup_executable.dll | [Starfield.exe Auto-Backup (SFSE)](https://www.nexusmods.com/starfield/mods/2544/) |
| AutoRecentSaveLoad.dll | [Auto Recent Save Load (SFSE)](https://www.nexusmods.com/starfield/mods/2962/) |
| BakaAchievementEnabler.dll | [Baka Achievement Enabler (SFSE)](https://www.nexusmods.com/starfield/mods/658/) |
| BakaKillMyGames.dll | [Baka Disable My Games Folder](https://www.nexusmods.com/starfield/mods/1599/) |
| BakaQuickFullSaves.dll | [Baka Quick Full Saves](https://www.nexusmods.com/starfield/mods/1750/) |
| BakaQuitGameFix.dll | [Baka Quit Game Fix](https://www.nexusmods.com/starfield/mods/1662/) |
| BayAndDocker-Count-Mod.dll | [No Landing Bay or Docker Limits](https://www.nexusmods.com/starfield/mods/6150/) |
| BetterConsole.dll | [BetterConsole - Console Replacer and MOD Menu](https://www.nexusmods.com/starfield/mods/3683/) |
| ClassicSprintingStarfield.dll | [Classic Sprinting (Hold to sprint)](https://www.nexusmods.com/starfield/mods/557/) |
| companions-never-lose-affinity.dll | [Companions Never Lose Affinity](https://www.nexusmods.com/starfield/mods/2682/) |
| ConsoleCommandRunner.dll | [Console Command Runner](https://www.nexusmods.com/starfield/mods/2740/) |
| CustomWindow.dll | [Custom Window](https://www.nexusmods.com/starfield/mods/2876/) |
| Discord_Presence_SFSE.dll | [Discord Rich Presence (SFSE)](https://www.nexusmods.com/starfield/mods/2545/) |
| Engine-Power-Mod.dll | [No Engine Power Limits](https://www.nexusmods.com/starfield/mods/1511/) |
| FastTravelRestrictions.dll | [Fast Travel Restrictions - Less Fast Travel (SFSE)](https://www.nexusmods.com/starfield/mods/3220/) |
| FlightControlsAutoalign.dll | [Flight Controls Autoalign](https://www.nexusmods.com/starfield/mods/1337/) |
| HeightRandomizer.dll | [Height Randomizer SFSE](https://www.nexusmods.com/starfield/mods/2525/) |
| KiLoaderSatelliteSFSE.dll | [KiLoader for Starfield](https://www.nexusmods.com/starfield/mods/3298/) |
| LandingGear-Count-Mod.dll | [No Minimum Landing Gear](https://www.nexusmods.com/starfield/mods/1479/) |
| libStarfieldKit.dll | [Disk Cache Enabler](https://www.nexusmods.com/starfield/mods/2245/) |
| longer-ship-name.dll | [Longer Ship Outpost and Item Names](https://www.nexusmods.com/starfield/mods/1635/) |
| NativeHDR.dll | [Native HDR and Color Banding Fix](https://www.nexusmods.com/starfield/mods/588/) |
| playerScaleFix.dll | [Player Scale Fix (SFSE)](https://www.nexusmods.com/starfield/mods/3405/) |
| po3_EnemyFriendlyFire.dll | [Enemy Friendly Fire (SFSE)](https://www.nexusmods.com/starfield/mods/614/) |
| po3_GravityAffectsCarryWeight.dll | [Gravity Affects Weight (SFSE)](https://www.nexusmods.com/starfield/mods/3048/) |
| po3_HoldToEquip.dll | [Hold To Equip Extended (SFSE)](https://www.nexusmods.com/starfield/mods/1956/) |
| po3_SimpleOffenseSuppression.dll | [Simple Offence Suppression SFSE](https://www.nexusmods.com/starfield/mods/4456/) |
| po3_SmartAiming.dll | [Smart Aiming SFSE - Third to First Person](https://www.nexusmods.com/starfield/mods/1302/) |
| po3_TweaksSF.dll | [powerofthree's Tweaks SFSE](https://www.nexusmods.com/starfield/mods/3621/) |
| Reactor-Class-Mod.dll | [No Reactor Class Requirement](https://www.nexusmods.com/starfield/mods/1482/) |
| Reactor-Count-Mod.dll | [No Reactor Limit](https://www.nexusmods.com/starfield/mods/1169/) |
| SaveRestrictions.dll | [Save Restrictions (SFSE)](https://www.nexusmods.com/starfield/mods/3020/) |
| SaveTweaks.dll | [Save Tweaks (SFSE)](https://www.nexusmods.com/starfield/mods/2937/) |
| SFSEASILoader.dll | [SFSE ASI Loader](https://www.nexusmods.com/starfield/mods/857/) |
| sfse_plugin_console.dll | [Console Output To File (SFSE Plugin)](https://www.nexusmods.com/starfield/mods/3142/) |
| SFPluginsTxtEnabler.dll | [Plugins.txt Enabler](https://www.nexusmods.com/starfield/mods/4157/) |
| SF-Zero-Weight.dll | [Zero Weight (SFSE)](https://www.nexusmods.com/starfield/mods/3475/) |
| Shield-Count-Mod.dll | [No Shield Limit](https://www.nexusmods.com/starfield/mods/1475/) |
| SimultaneousInput.dll | [Simultaneous Mouse and Gamepad](https://www.nexusmods.com/starfield/mods/1603/) |
| SprintStutteringFix.dll | [Sprint Stuttering Fix](https://www.nexusmods.com/starfield/mods/884/) |
| Starfield-Save-Previews.dll | [Starfield Save Previews](https://www.nexusmods.com/starfield/mods/3846/) |
| Starfield-Silent-Voice.dll | [Starfield Silent Voice](https://www.nexusmods.com/starfield/mods/3153/) |
| Starfield_SlowerThanLight.dll | [SlowerThanLight - Fly in a star system](https://www.nexusmods.com/starfield/mods/3541/) |
| Stew_ManualReload.dll | [Stew - Manual Reload](https://www.nexusmods.com/starfield/mods/4451/) |
| Stew_NoLockpickOpen.dll | [No Lockpick Activate](https://www.nexusmods.com/starfield/mods/3286/) |
| Stew_OverencumberedFastTravel.dll | [Stew - Overencumbered Fast Travel](https://www.nexusmods.com/starfield/mods/3555/) |
| StreamlineNative.dll | [Streamline Native (Frame Gen - DLSS - Reflex Integration)](https://www.nexusmods.com/starfield/mods/2751/) |
| WeaponModelFOVSwap.dll | [SFSE - Weapon Model FOV setter](https://www.nexusmods.com/starfield/mods/1331/) |
| Weapon-Power-Mod.dll | [No Weapon Power or Count Limits](https://www.nexusmods.com/starfield/mods/1510/) |
| WeaponSwapStutteringFix.dll | [Weapon Swap Stuttering Fix](https://www.nexusmods.com/starfield/mods/2830/) |
